version: '3.8'

services:
  mysql:
    restart: always
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./sql_commands.sql:/docker-entrypoint-initdb.d/sql_commands.sql


  webserver:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9980:9980"
    depends_on:
      - mysql